name: Build Tomcat

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out your repo
        uses: actions/checkout@v4

      - name: List project files and Java version
        run: |
          ls -ltr
          java -version

      - name: Check out Apache Tomcat
        uses: actions/checkout@v4
        with:
          repository: apache/tomcat
          ref: main
          path: ./tomcat

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Ant
        run: sudo apt-get update && sudo apt-get install -y ant

      - name: List files again + Java version
        run: |
          ls -ltr
          java -version

      - name: Copy tomcat-users.xml into Tomcat config
        run: cp -v tomcat-users.xml ./tomcat/conf/tomcat-users.xml

      - name: Compile Tomcat
        run: |
          cd ./tomcat
          ant
